# Configuration for pre-commit: A framework for managing and maintaining multi-language pre-commit hooks.
# https://pre-commit.com/
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: WTFPL
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: check-byte-order-marker

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
    - id: shellcheck
